blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
templates:
  - name: Bug Report
    about: Please fill out the fields below completely in order to resolve the issue.
    filename: bug_report.md